export enum ATypes {
  FETCH_SUCCESS = "FETCH_SUCCESS",
  FETCH_ERROR = "FETCH_ERROR",
  FETCH_LOADING = "FETCH_LOADING",
  SET_THEME = "SET_THEME",
  SET_USER = "SET_USER",
  SET_COLOR = "SET_COLOR",
  SET_LINE = "SET_LINE",
  GET_LINES = "GET_LINES",
  LOG_OUT = "LOG_OUT",
  INITIAL_THEME = "INITIAL_THEME",
}
